# First Project. Building a simple set of functions that should be able to take in user input and save that information to a file.
# The user should also be able to read the file and see the information that they have saved.



from datetime import datetime
import re


datafile = "data.csv"   # Name of the csv file of which locally will store all the data needed in the program generated by user inputs.               


def firstname ():   # Function that requires user to input their first name with at least 3 characters and make that name case insensitive. Also strips all whitespace.
    
    try:
        while True:
                ask = input ("Please enter your first name: ").strip().lower()
                if len(ask) > 2:
                    return True, ask
                else:
                    print ("Please enter a valid first name. A minimum of 3 characters are required.")
    except Exception as e:
        print (f"An error occurred {e}")
        return False, None    


def lastname ():    # Function that requires user to input their last name with at least 3 characters and make that name case insensitive. Also strips all whitespace.    
    
    try:
        while True:
            ask = input ("Please enter your last name: ").strip().lower()
            if len(ask) > 2:
                return True, ask
            else:
                print ("Please enter a valid last name. A minimum of 3 characters are required.")
    except Exception as e:
        print (f"An error occurred {e}")
        return False, None  


def ValidDoB ():    # Function that requires user to input their date of birth in a specific format. If that condition is not met, the loop continues until True.
    while True:
        try:
            dob = input ("Please enter a valid Date of Birth using the format dd/mm/yyyy: ")
            datetime.strptime(dob,"%d/%m/%Y") 
            return dob
        except ValueError as ve:
            print (f"There has been an error {ve}")


def username(): # Function that requires user to input their desired username however false is returned if there are special characters or any numbers.
    try:
        while True:
            user = input("Please enter a username. The username must be between 3 characters or more and not include any numbers.: ")
            if not user:
                print("Username cannot be empty. Please try again.")
                continue
            if len(user) < 3 or not any(char.isdigit() for char in user) or re.search(r"[^\w\s]",user):
                print ("Your password has been successfully added to your account")
                return True, user
        else:
            return False, None

    except Exception as e:
        print (f"There seems to be an error {e}")
        return False, None


def main ():    # Function that pieces together the main workflow of the program after the functions before are written.
    valid_fname, first_name = firstname()
    if valid_fname:
        valid_lname, last_name = lastname()
        if valid_lname:
            dob = ValidDoB()
            if dob:
                valid_username, user_name = username()
                if valid_username:
                    print ("All information is correct. Thank you!")
                    WriteToFile(first_name, last_name, dob, user_name, datafile)
                else:
                    print ("Your password is invalid")
            else:
                print ("Please enter a valid Date of Birth with the correct format YYYY-MM-DD ")
        else:
            print ("Please enter a valid last name. A minimum of 3 characters are required. ")
    else:
        print ("Please enter a valid first name. A minimum of 3 characters are required. ")
                
                


def WriteToFile(firstname, lastname, dob, username, datafile):
    try:
        
        filetowrite = f"{firstname},{lastname},{dob},{username}"
        
        
        with open(datafile, "a") as file:
            file.write(filetowrite + "\n")
            print("Data written to the Data file successfully.")
    
    except Exception as e:
        print(f"There was an error: {e}")

if __name__ == "__main__":
    main()

  






